/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as AboutRouteImport } from './routes/about'
import { Route as SplatRouteImport } from './routes/$'
import { Route as ServicesRouteRouteImport } from './routes/services/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services/index'
import { Route as ContactIndexRouteImport } from './routes/contact/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as SitemapXmlRouteImport } from './routes/sitemap.xml'
import { Route as ServicesStarterKitRouteImport } from './routes/services/starter-kit'
import { Route as ServicesSeoRouteImport } from './routes/services/seo'
import { Route as RobotsTxtRouteImport } from './routes/robots.txt'
import { Route as LegalTermsRouteImport } from './routes/legal/terms'
import { Route as LegalPrivacyRouteImport } from './routes/legal/privacy'
import { Route as LegalCookiesRouteImport } from './routes/legal/cookies'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminSeoRouteImport } from './routes/admin/seo'
import { Route as AdminSecurityRouteImport } from './routes/admin/security'
import { Route as AdminRolesRouteImport } from './routes/admin/roles'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminForgotPasswordRouteImport } from './routes/admin/forgot-password'
import { Route as AdminEmailRouteImport } from './routes/admin/email'
import { Route as AdminCrmRouteImport } from './routes/admin/crm'
import { Route as AdminCreateAdminRouteImport } from './routes/admin/create-admin'
import { Route as AdminCmsRouteImport } from './routes/admin/cms'
import { Route as ServicesWebSaasRouteImport } from './routes/services/web/saas'
import { Route as ServicesWebPythonBackendRouteImport } from './routes/services/web/python-backend'
import { Route as ServicesWebFullStackRouteImport } from './routes/services/web/full-stack'
import { Route as ServicesWebAuthRouteImport } from './routes/services/web/auth'
import { Route as ServicesDigitalMarketingPaidAdvertisingRouteImport } from './routes/services/digital-marketing/paid-advertising'
import { Route as ServicesDigitalMarketingCroRouteImport } from './routes/services/digital-marketing/cro'
import { Route as ServicesDigitalMarketingContentStrategyRouteImport } from './routes/services/digital-marketing/content-strategy'
import { Route as ServicesCreativeVideoProductionRouteImport } from './routes/services/creative/video-production'
import { Route as ServicesCreativeGraphicDesignRouteImport } from './routes/services/creative/graphic-design'
import { Route as ServicesAiPromptEngineeringRouteImport } from './routes/services/ai/prompt-engineering'
import { Route as ServicesAiLlmRouteImport } from './routes/services/ai/llm'
import { Route as ServicesAiCvNlpRouteImport } from './routes/services/ai/cv-nlp'
import { Route as ServicesAiChatbotsRouteImport } from './routes/services/ai/chatbots'

const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRouteRoute = ServicesRouteRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRouteRoute,
} as any)
const ContactIndexRoute = ContactIndexRouteImport.update({
  id: '/contact/',
  path: '/contact/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const SitemapXmlRoute = SitemapXmlRouteImport.update({
  id: '/sitemap/xml',
  path: '/sitemap/xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesStarterKitRoute = ServicesStarterKitRouteImport.update({
  id: '/starter-kit',
  path: '/starter-kit',
  getParentRoute: () => ServicesRouteRoute,
} as any)
const ServicesSeoRoute = ServicesSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => ServicesRouteRoute,
} as any)
const RobotsTxtRoute = RobotsTxtRouteImport.update({
  id: '/robots/txt',
  path: '/robots/txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalCookiesRoute = LegalCookiesRouteImport.update({
  id: '/legal/cookies',
  path: '/legal/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSeoRoute = AdminSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSecurityRoute = AdminSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminForgotPasswordRoute = AdminForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEmailRoute = AdminEmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCrmRoute = AdminCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCreateAdminRoute = AdminCreateAdminRouteImport.update({
  id: '/create-admin',
  path: '/create-admin',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCmsRoute = AdminCmsRouteImport.update({
  id: '/cms',
  path: '/cms',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ServicesWebSaasRoute = ServicesWebSaasRouteImport.update({
  id: '/web/saas',
  path: '/web/saas',
  getParentRoute: () => ServicesRouteRoute,
} as any)
const ServicesWebPythonBackendRoute =
  ServicesWebPythonBackendRouteImport.update({
    id: '/web/python-backend',
    path: '/web/python-backend',
    getParentRoute: () => ServicesRouteRoute,
  } as any)
const ServicesWebFullStackRoute = ServicesWebFullStackRouteImport.update({
  id: '/web/full-stack',
  path: '/web/full-stack',
  getParentRoute: () => ServicesRouteRoute,
} as any)
const ServicesWebAuthRoute = ServicesWebAuthRouteImport.update({
  id: '/web/auth',
  path: '/web/auth',
  getParentRoute: () => ServicesRouteRoute,
} as any)
const ServicesDigitalMarketingPaidAdvertisingRoute =
  ServicesDigitalMarketingPaidAdvertisingRouteImport.update({
    id: '/digital-marketing/paid-advertising',
    path: '/digital-marketing/paid-advertising',
    getParentRoute: () => ServicesRouteRoute,
  } as any)
const ServicesDigitalMarketingCroRoute =
  ServicesDigitalMarketingCroRouteImport.update({
    id: '/digital-marketing/cro',
    path: '/digital-marketing/cro',
    getParentRoute: () => ServicesRouteRoute,
  } as any)
const ServicesDigitalMarketingContentStrategyRoute =
  ServicesDigitalMarketingContentStrategyRouteImport.update({
    id: '/digital-marketing/content-strategy',
    path: '/digital-marketing/content-strategy',
    getParentRoute: () => ServicesRouteRoute,
  } as any)
const ServicesCreativeVideoProductionRoute =
  ServicesCreativeVideoProductionRouteImport.update({
    id: '/creative/video-production',
    path: '/creative/video-production',
    getParentRoute: () => ServicesRouteRoute,
  } as any)
const ServicesCreativeGraphicDesignRoute =
  ServicesCreativeGraphicDesignRouteImport.update({
    id: '/creative/graphic-design',
    path: '/creative/graphic-design',
    getParentRoute: () => ServicesRouteRoute,
  } as any)
const ServicesAiPromptEngineeringRoute =
  ServicesAiPromptEngineeringRouteImport.update({
    id: '/ai/prompt-engineering',
    path: '/ai/prompt-engineering',
    getParentRoute: () => ServicesRouteRoute,
  } as any)
const ServicesAiLlmRoute = ServicesAiLlmRouteImport.update({
  id: '/ai/llm',
  path: '/ai/llm',
  getParentRoute: () => ServicesRouteRoute,
} as any)
const ServicesAiCvNlpRoute = ServicesAiCvNlpRouteImport.update({
  id: '/ai/cv-nlp',
  path: '/ai/cv-nlp',
  getParentRoute: () => ServicesRouteRoute,
} as any)
const ServicesAiChatbotsRoute = ServicesAiChatbotsRouteImport.update({
  id: '/ai/chatbots',
  path: '/ai/chatbots',
  getParentRoute: () => ServicesRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/services': typeof ServicesRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/portfolio': typeof PortfolioRoute
  '/resources': typeof ResourcesRoute
  '/admin/cms': typeof AdminCmsRoute
  '/admin/create-admin': typeof AdminCreateAdminRoute
  '/admin/crm': typeof AdminCrmRoute
  '/admin/email': typeof AdminEmailRoute
  '/admin/forgot-password': typeof AdminForgotPasswordRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/robots/txt': typeof RobotsTxtRoute
  '/services/seo': typeof ServicesSeoRoute
  '/services/starter-kit': typeof ServicesStarterKitRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/admin/': typeof AdminIndexRoute
  '/contact/': typeof ContactIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/services/ai/chatbots': typeof ServicesAiChatbotsRoute
  '/services/ai/cv-nlp': typeof ServicesAiCvNlpRoute
  '/services/ai/llm': typeof ServicesAiLlmRoute
  '/services/ai/prompt-engineering': typeof ServicesAiPromptEngineeringRoute
  '/services/creative/graphic-design': typeof ServicesCreativeGraphicDesignRoute
  '/services/creative/video-production': typeof ServicesCreativeVideoProductionRoute
  '/services/digital-marketing/content-strategy': typeof ServicesDigitalMarketingContentStrategyRoute
  '/services/digital-marketing/cro': typeof ServicesDigitalMarketingCroRoute
  '/services/digital-marketing/paid-advertising': typeof ServicesDigitalMarketingPaidAdvertisingRoute
  '/services/web/auth': typeof ServicesWebAuthRoute
  '/services/web/full-stack': typeof ServicesWebFullStackRoute
  '/services/web/python-backend': typeof ServicesWebPythonBackendRoute
  '/services/web/saas': typeof ServicesWebSaasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/portfolio': typeof PortfolioRoute
  '/resources': typeof ResourcesRoute
  '/admin/cms': typeof AdminCmsRoute
  '/admin/create-admin': typeof AdminCreateAdminRoute
  '/admin/crm': typeof AdminCrmRoute
  '/admin/email': typeof AdminEmailRoute
  '/admin/forgot-password': typeof AdminForgotPasswordRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/robots/txt': typeof RobotsTxtRoute
  '/services/seo': typeof ServicesSeoRoute
  '/services/starter-kit': typeof ServicesStarterKitRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/admin': typeof AdminIndexRoute
  '/contact': typeof ContactIndexRoute
  '/services': typeof ServicesIndexRoute
  '/services/ai/chatbots': typeof ServicesAiChatbotsRoute
  '/services/ai/cv-nlp': typeof ServicesAiCvNlpRoute
  '/services/ai/llm': typeof ServicesAiLlmRoute
  '/services/ai/prompt-engineering': typeof ServicesAiPromptEngineeringRoute
  '/services/creative/graphic-design': typeof ServicesCreativeGraphicDesignRoute
  '/services/creative/video-production': typeof ServicesCreativeVideoProductionRoute
  '/services/digital-marketing/content-strategy': typeof ServicesDigitalMarketingContentStrategyRoute
  '/services/digital-marketing/cro': typeof ServicesDigitalMarketingCroRoute
  '/services/digital-marketing/paid-advertising': typeof ServicesDigitalMarketingPaidAdvertisingRoute
  '/services/web/auth': typeof ServicesWebAuthRoute
  '/services/web/full-stack': typeof ServicesWebFullStackRoute
  '/services/web/python-backend': typeof ServicesWebPythonBackendRoute
  '/services/web/saas': typeof ServicesWebSaasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/services': typeof ServicesRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/portfolio': typeof PortfolioRoute
  '/resources': typeof ResourcesRoute
  '/admin/cms': typeof AdminCmsRoute
  '/admin/create-admin': typeof AdminCreateAdminRoute
  '/admin/crm': typeof AdminCrmRoute
  '/admin/email': typeof AdminEmailRoute
  '/admin/forgot-password': typeof AdminForgotPasswordRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/robots/txt': typeof RobotsTxtRoute
  '/services/seo': typeof ServicesSeoRoute
  '/services/starter-kit': typeof ServicesStarterKitRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/admin/': typeof AdminIndexRoute
  '/contact/': typeof ContactIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/services/ai/chatbots': typeof ServicesAiChatbotsRoute
  '/services/ai/cv-nlp': typeof ServicesAiCvNlpRoute
  '/services/ai/llm': typeof ServicesAiLlmRoute
  '/services/ai/prompt-engineering': typeof ServicesAiPromptEngineeringRoute
  '/services/creative/graphic-design': typeof ServicesCreativeGraphicDesignRoute
  '/services/creative/video-production': typeof ServicesCreativeVideoProductionRoute
  '/services/digital-marketing/content-strategy': typeof ServicesDigitalMarketingContentStrategyRoute
  '/services/digital-marketing/cro': typeof ServicesDigitalMarketingCroRoute
  '/services/digital-marketing/paid-advertising': typeof ServicesDigitalMarketingPaidAdvertisingRoute
  '/services/web/auth': typeof ServicesWebAuthRoute
  '/services/web/full-stack': typeof ServicesWebFullStackRoute
  '/services/web/python-backend': typeof ServicesWebPythonBackendRoute
  '/services/web/saas': typeof ServicesWebSaasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/services'
    | '/$'
    | '/about'
    | '/portfolio'
    | '/resources'
    | '/admin/cms'
    | '/admin/create-admin'
    | '/admin/crm'
    | '/admin/email'
    | '/admin/forgot-password'
    | '/admin/login'
    | '/admin/roles'
    | '/admin/security'
    | '/admin/seo'
    | '/admin/settings'
    | '/legal/cookies'
    | '/legal/privacy'
    | '/legal/terms'
    | '/robots/txt'
    | '/services/seo'
    | '/services/starter-kit'
    | '/sitemap/xml'
    | '/admin/'
    | '/contact/'
    | '/services/'
    | '/services/ai/chatbots'
    | '/services/ai/cv-nlp'
    | '/services/ai/llm'
    | '/services/ai/prompt-engineering'
    | '/services/creative/graphic-design'
    | '/services/creative/video-production'
    | '/services/digital-marketing/content-strategy'
    | '/services/digital-marketing/cro'
    | '/services/digital-marketing/paid-advertising'
    | '/services/web/auth'
    | '/services/web/full-stack'
    | '/services/web/python-backend'
    | '/services/web/saas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/about'
    | '/portfolio'
    | '/resources'
    | '/admin/cms'
    | '/admin/create-admin'
    | '/admin/crm'
    | '/admin/email'
    | '/admin/forgot-password'
    | '/admin/login'
    | '/admin/roles'
    | '/admin/security'
    | '/admin/seo'
    | '/admin/settings'
    | '/legal/cookies'
    | '/legal/privacy'
    | '/legal/terms'
    | '/robots/txt'
    | '/services/seo'
    | '/services/starter-kit'
    | '/sitemap/xml'
    | '/admin'
    | '/contact'
    | '/services'
    | '/services/ai/chatbots'
    | '/services/ai/cv-nlp'
    | '/services/ai/llm'
    | '/services/ai/prompt-engineering'
    | '/services/creative/graphic-design'
    | '/services/creative/video-production'
    | '/services/digital-marketing/content-strategy'
    | '/services/digital-marketing/cro'
    | '/services/digital-marketing/paid-advertising'
    | '/services/web/auth'
    | '/services/web/full-stack'
    | '/services/web/python-backend'
    | '/services/web/saas'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/services'
    | '/$'
    | '/about'
    | '/portfolio'
    | '/resources'
    | '/admin/cms'
    | '/admin/create-admin'
    | '/admin/crm'
    | '/admin/email'
    | '/admin/forgot-password'
    | '/admin/login'
    | '/admin/roles'
    | '/admin/security'
    | '/admin/seo'
    | '/admin/settings'
    | '/legal/cookies'
    | '/legal/privacy'
    | '/legal/terms'
    | '/robots/txt'
    | '/services/seo'
    | '/services/starter-kit'
    | '/sitemap/xml'
    | '/admin/'
    | '/contact/'
    | '/services/'
    | '/services/ai/chatbots'
    | '/services/ai/cv-nlp'
    | '/services/ai/llm'
    | '/services/ai/prompt-engineering'
    | '/services/creative/graphic-design'
    | '/services/creative/video-production'
    | '/services/digital-marketing/content-strategy'
    | '/services/digital-marketing/cro'
    | '/services/digital-marketing/paid-advertising'
    | '/services/web/auth'
    | '/services/web/full-stack'
    | '/services/web/python-backend'
    | '/services/web/saas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  ServicesRouteRoute: typeof ServicesRouteRouteWithChildren
  SplatRoute: typeof SplatRoute
  AboutRoute: typeof AboutRoute
  PortfolioRoute: typeof PortfolioRoute
  ResourcesRoute: typeof ResourcesRoute
  LegalCookiesRoute: typeof LegalCookiesRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
  RobotsTxtRoute: typeof RobotsTxtRoute
  SitemapXmlRoute: typeof SitemapXmlRoute
  ContactIndexRoute: typeof ContactIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRouteRoute
    }
    '/contact/': {
      id: '/contact/'
      path: '/contact'
      fullPath: '/contact/'
      preLoaderRoute: typeof ContactIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/sitemap/xml': {
      id: '/sitemap/xml'
      path: '/sitemap/xml'
      fullPath: '/sitemap/xml'
      preLoaderRoute: typeof SitemapXmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/starter-kit': {
      id: '/services/starter-kit'
      path: '/starter-kit'
      fullPath: '/services/starter-kit'
      preLoaderRoute: typeof ServicesStarterKitRouteImport
      parentRoute: typeof ServicesRouteRoute
    }
    '/services/seo': {
      id: '/services/seo'
      path: '/seo'
      fullPath: '/services/seo'
      preLoaderRoute: typeof ServicesSeoRouteImport
      parentRoute: typeof ServicesRouteRoute
    }
    '/robots/txt': {
      id: '/robots/txt'
      path: '/robots/txt'
      fullPath: '/robots/txt'
      preLoaderRoute: typeof RobotsTxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/cookies': {
      id: '/legal/cookies'
      path: '/legal/cookies'
      fullPath: '/legal/cookies'
      preLoaderRoute: typeof LegalCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/seo': {
      id: '/admin/seo'
      path: '/seo'
      fullPath: '/admin/seo'
      preLoaderRoute: typeof AdminSeoRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/security': {
      id: '/admin/security'
      path: '/security'
      fullPath: '/admin/security'
      preLoaderRoute: typeof AdminSecurityRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/forgot-password': {
      id: '/admin/forgot-password'
      path: '/forgot-password'
      fullPath: '/admin/forgot-password'
      preLoaderRoute: typeof AdminForgotPasswordRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/email': {
      id: '/admin/email'
      path: '/email'
      fullPath: '/admin/email'
      preLoaderRoute: typeof AdminEmailRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/crm': {
      id: '/admin/crm'
      path: '/crm'
      fullPath: '/admin/crm'
      preLoaderRoute: typeof AdminCrmRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/create-admin': {
      id: '/admin/create-admin'
      path: '/create-admin'
      fullPath: '/admin/create-admin'
      preLoaderRoute: typeof AdminCreateAdminRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/cms': {
      id: '/admin/cms'
      path: '/cms'
      fullPath: '/admin/cms'
      preLoaderRoute: typeof AdminCmsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/services/web/saas': {
      id: '/services/web/saas'
      path: '/web/saas'
      fullPath: '/services/web/saas'
      preLoaderRoute: typeof ServicesWebSaasRouteImport
      parentRoute: typeof ServicesRouteRoute
    }
    '/services/web/python-backend': {
      id: '/services/web/python-backend'
      path: '/web/python-backend'
      fullPath: '/services/web/python-backend'
      preLoaderRoute: typeof ServicesWebPythonBackendRouteImport
      parentRoute: typeof ServicesRouteRoute
    }
    '/services/web/full-stack': {
      id: '/services/web/full-stack'
      path: '/web/full-stack'
      fullPath: '/services/web/full-stack'
      preLoaderRoute: typeof ServicesWebFullStackRouteImport
      parentRoute: typeof ServicesRouteRoute
    }
    '/services/web/auth': {
      id: '/services/web/auth'
      path: '/web/auth'
      fullPath: '/services/web/auth'
      preLoaderRoute: typeof ServicesWebAuthRouteImport
      parentRoute: typeof ServicesRouteRoute
    }
    '/services/digital-marketing/paid-advertising': {
      id: '/services/digital-marketing/paid-advertising'
      path: '/digital-marketing/paid-advertising'
      fullPath: '/services/digital-marketing/paid-advertising'
      preLoaderRoute: typeof ServicesDigitalMarketingPaidAdvertisingRouteImport
      parentRoute: typeof ServicesRouteRoute
    }
    '/services/digital-marketing/cro': {
      id: '/services/digital-marketing/cro'
      path: '/digital-marketing/cro'
      fullPath: '/services/digital-marketing/cro'
      preLoaderRoute: typeof ServicesDigitalMarketingCroRouteImport
      parentRoute: typeof ServicesRouteRoute
    }
    '/services/digital-marketing/content-strategy': {
      id: '/services/digital-marketing/content-strategy'
      path: '/digital-marketing/content-strategy'
      fullPath: '/services/digital-marketing/content-strategy'
      preLoaderRoute: typeof ServicesDigitalMarketingContentStrategyRouteImport
      parentRoute: typeof ServicesRouteRoute
    }
    '/services/creative/video-production': {
      id: '/services/creative/video-production'
      path: '/creative/video-production'
      fullPath: '/services/creative/video-production'
      preLoaderRoute: typeof ServicesCreativeVideoProductionRouteImport
      parentRoute: typeof ServicesRouteRoute
    }
    '/services/creative/graphic-design': {
      id: '/services/creative/graphic-design'
      path: '/creative/graphic-design'
      fullPath: '/services/creative/graphic-design'
      preLoaderRoute: typeof ServicesCreativeGraphicDesignRouteImport
      parentRoute: typeof ServicesRouteRoute
    }
    '/services/ai/prompt-engineering': {
      id: '/services/ai/prompt-engineering'
      path: '/ai/prompt-engineering'
      fullPath: '/services/ai/prompt-engineering'
      preLoaderRoute: typeof ServicesAiPromptEngineeringRouteImport
      parentRoute: typeof ServicesRouteRoute
    }
    '/services/ai/llm': {
      id: '/services/ai/llm'
      path: '/ai/llm'
      fullPath: '/services/ai/llm'
      preLoaderRoute: typeof ServicesAiLlmRouteImport
      parentRoute: typeof ServicesRouteRoute
    }
    '/services/ai/cv-nlp': {
      id: '/services/ai/cv-nlp'
      path: '/ai/cv-nlp'
      fullPath: '/services/ai/cv-nlp'
      preLoaderRoute: typeof ServicesAiCvNlpRouteImport
      parentRoute: typeof ServicesRouteRoute
    }
    '/services/ai/chatbots': {
      id: '/services/ai/chatbots'
      path: '/ai/chatbots'
      fullPath: '/services/ai/chatbots'
      preLoaderRoute: typeof ServicesAiChatbotsRouteImport
      parentRoute: typeof ServicesRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminCmsRoute: typeof AdminCmsRoute
  AdminCreateAdminRoute: typeof AdminCreateAdminRoute
  AdminCrmRoute: typeof AdminCrmRoute
  AdminEmailRoute: typeof AdminEmailRoute
  AdminForgotPasswordRoute: typeof AdminForgotPasswordRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminSecurityRoute: typeof AdminSecurityRoute
  AdminSeoRoute: typeof AdminSeoRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminCmsRoute: AdminCmsRoute,
  AdminCreateAdminRoute: AdminCreateAdminRoute,
  AdminCrmRoute: AdminCrmRoute,
  AdminEmailRoute: AdminEmailRoute,
  AdminForgotPasswordRoute: AdminForgotPasswordRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminSecurityRoute: AdminSecurityRoute,
  AdminSeoRoute: AdminSeoRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface ServicesRouteRouteChildren {
  ServicesSeoRoute: typeof ServicesSeoRoute
  ServicesStarterKitRoute: typeof ServicesStarterKitRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  ServicesAiChatbotsRoute: typeof ServicesAiChatbotsRoute
  ServicesAiCvNlpRoute: typeof ServicesAiCvNlpRoute
  ServicesAiLlmRoute: typeof ServicesAiLlmRoute
  ServicesAiPromptEngineeringRoute: typeof ServicesAiPromptEngineeringRoute
  ServicesCreativeGraphicDesignRoute: typeof ServicesCreativeGraphicDesignRoute
  ServicesCreativeVideoProductionRoute: typeof ServicesCreativeVideoProductionRoute
  ServicesDigitalMarketingContentStrategyRoute: typeof ServicesDigitalMarketingContentStrategyRoute
  ServicesDigitalMarketingCroRoute: typeof ServicesDigitalMarketingCroRoute
  ServicesDigitalMarketingPaidAdvertisingRoute: typeof ServicesDigitalMarketingPaidAdvertisingRoute
  ServicesWebAuthRoute: typeof ServicesWebAuthRoute
  ServicesWebFullStackRoute: typeof ServicesWebFullStackRoute
  ServicesWebPythonBackendRoute: typeof ServicesWebPythonBackendRoute
  ServicesWebSaasRoute: typeof ServicesWebSaasRoute
}

const ServicesRouteRouteChildren: ServicesRouteRouteChildren = {
  ServicesSeoRoute: ServicesSeoRoute,
  ServicesStarterKitRoute: ServicesStarterKitRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  ServicesAiChatbotsRoute: ServicesAiChatbotsRoute,
  ServicesAiCvNlpRoute: ServicesAiCvNlpRoute,
  ServicesAiLlmRoute: ServicesAiLlmRoute,
  ServicesAiPromptEngineeringRoute: ServicesAiPromptEngineeringRoute,
  ServicesCreativeGraphicDesignRoute: ServicesCreativeGraphicDesignRoute,
  ServicesCreativeVideoProductionRoute: ServicesCreativeVideoProductionRoute,
  ServicesDigitalMarketingContentStrategyRoute:
    ServicesDigitalMarketingContentStrategyRoute,
  ServicesDigitalMarketingCroRoute: ServicesDigitalMarketingCroRoute,
  ServicesDigitalMarketingPaidAdvertisingRoute:
    ServicesDigitalMarketingPaidAdvertisingRoute,
  ServicesWebAuthRoute: ServicesWebAuthRoute,
  ServicesWebFullStackRoute: ServicesWebFullStackRoute,
  ServicesWebPythonBackendRoute: ServicesWebPythonBackendRoute,
  ServicesWebSaasRoute: ServicesWebSaasRoute,
}

const ServicesRouteRouteWithChildren = ServicesRouteRoute._addFileChildren(
  ServicesRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  ServicesRouteRoute: ServicesRouteRouteWithChildren,
  SplatRoute: SplatRoute,
  AboutRoute: AboutRoute,
  PortfolioRoute: PortfolioRoute,
  ResourcesRoute: ResourcesRoute,
  LegalCookiesRoute: LegalCookiesRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
  RobotsTxtRoute: RobotsTxtRoute,
  SitemapXmlRoute: SitemapXmlRoute,
  ContactIndexRoute: ContactIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
